.github/workflows/format.yml
Ref: https://github.com/creyD/prettier_action/issues/113#issuecomment-1436021099
=> ci: update to use `prettier_action@4.3`

cypress/basic/cypress.config.js, cypress/manual-mode/cypress.config.js, cypress/multi-page/cypress.config.js, playwright/basic/tests/login.js, playwright/manual-mode/tests/login.js
Closes: https://github.com/dequelabs/watcher-examples/issues/123
=> chore: add default value for `SERVER_URL`

.github/workflows/update.yml, cypress/basic/package.json, cypress/manual-mode/package.json, cypress/multi-page/package.json, playwright/basic/package.json, playwright/manual-mode/package.json
Closes: https://github.com/dequelabs/watcher-examples/issues/122
=> chore: use latest `@axe-core/watcher` release

.gitignore, playwright-test/basic/package.json, playwright-test/basic/playwright.config.js, playwright-test/basic/tests/fixtures.js, playwright-test/basic/tests/home.spec.js
=> feat(playwright-test): Add a basic JS example

playwright/typescript-multi-page/package.json, playwright/typescript-multi-page/tests/forgot-password.test.ts, playwright/typescript-multi-page/tests/home.test.ts, playwright/typescript-multi-page/tests/login.test.ts, playwright/typescript-multi-page/tests/setup.ts, playwright/typescript-multi-page/tsconfig.json
=> feat(playwright): Add a TypeScript multi-page example

puppeteer/basic/package.json, puppeteer/basic/tests/login.js, puppeteer/typescript-multi-page/package.json, puppeteer/typescript-multi-page/tests/forgot-password.test.ts, puppeteer/typescript-multi-page/tests/home.test.ts, puppeteer/typescript-multi-page/tests/login.test.ts, puppeteer/typescript-multi-page/tests/setup.ts, puppeteer/typescript-multi-page/tsconfig.json
Blocked by https://github.com/dequelabs/jazzband/pull/473
Closes #136
Closes #137
=> feat: Add Puppeteer examples

selenium-webdriver/basic/package.json, selenium-webdriver/basic/tests/login.js, selenium-webdriver/typescript-multi-page/package.json, selenium-webdriver/typescript-multi-page/tests/forgot-password.test.ts, selenium-webdriver/typescript-multi-page/tests/home.test.ts, selenium-webdriver/typescript-multi-page/tests/login.test.ts, selenium-webdriver/typescript-multi-page/tests/setup.ts, selenium-webdriver/typescript-multi-page/tsconfig.json
=> feat: Add Selenium Webdriver examples

puppeteer/basic/tests/login.js
Closes: https://github.com/dequelabs/watcher-examples/issues/148
=> fix(puppeteer): amend import to use `wrapPuppeteer`

.eslintrc.js, wdio-with-config/typescript-multi-page/forgot-password.test.ts, wdio-with-config/typescript-multi-page/home.test.ts, wdio-with-config/typescript-multi-page/login.test.ts, wdio-with-config/typescript-multi-page/package.json, wdio-with-config/typescript-multi-page/setup.ts, wdio-with-config/typescript-multi-page/tsconfig.json, wdio-with-config/typescript-multi-page/wdio.config.ts, wdio/typescript-multi-page/forgot-password.test.ts, wdio/typescript-multi-page/home.test.ts, wdio/typescript-multi-page/login.test.ts, wdio/typescript-multi-page/package.json, wdio/typescript-multi-page/setup.ts, wdio/typescript-multi-page/tsconfig.json
Closes https://github.com/dequelabs/walnut/issues/5180 (again)
=> feat: Add WDIO and WDIO with config examples

.github/workflows/format.yml, .github/workflows/semantic-pr-footer.yml, .github/workflows/test.yml, .github/workflows/update.yml
Closes: #172 
Closes: #173
No QA required
=> ci: add timeouts for each GHA workflow and QA pr footer

webdriverjs/basic/tests/login.js
Simply adds `flush()` in the WebDriverJS `login.js` `afterEach` example
ref: #177
=> fix(webdriverjs): add flush in aftereach

.github/workflows/test.yml
=> ci: name jobs for ease of use for branch rule enforcement

.github/CODEOWNERS
QA notes: I like doggies 🐶 🐕 🦮 🐩 🐕‍🦺
=> ci: Fix code owners (now bass, not api)

.github/workflows/test.yml
QA notes: Harris is Harry Potter
=> ci: Bump actions/{checkout,setup-node}

.github/workflows/test.yml
We have to do https://github.com/dequelabs/watcher-examples/issues/216
no qa required
=> ci: defer smoke-tests

cypress/manual-mode/cypress/e2e/login.cy.js, cypress/manual-mode/package.json, playwright-test/manual-mode/package.json, playwright-test/manual-mode/playwright.config.ts, playwright-test/manual-mode/tests/fixtures.ts, playwright-test/manual-mode/tests/login.spec.ts, playwright-test/manual-mode/tsconfig.json, playwright/manual-mode/package.json, playwright/manual-mode/tests/login.js, puppeteer/manual-mode/package.json, puppeteer/manual-mode/tests/login.js, wdio/manual-mode/login.test.ts, wdio/manual-mode/package.json, wdio/manual-mode/setup.ts, wdio/manual-mode/tsconfig.json, webdriverjs/manual-mode/package.json, webdriverjs/manual-mode/tests/login.js
- This is simple PR, Which demonstrates the power of `@axe-core/watcher` manual mode where you can control the analyse s whenever needed and also have a block of code where you want to automatic mode. 
Closes:  #209, #210, #211, #214, #213, #212
=> chore:  Update/Create Manual Mode Examples 

webdriverjs/manual-mode/tests/login.js
- This PR contains some changes around webdriverjs 
Closes: https://github.com/dequelabs/jazzband/issues/2064
=> fix(webdriverjs): added flush() in manual-mode

.github/workflows/test.yml, puppeteer/basic/package.json, puppeteer/basic/tests/login.js, puppeteer/manual-mode/package.json, puppeteer/manual-mode/tests/login.js, puppeteer/typescript-multi-page/package.json, puppeteer/typescript-multi-page/tests/setup.ts, wdio/manual-mode/package.json, wdio/test-runner/typescript/package.json, wdio/typescript-multi-page/package.json, wdio/v7/typescript-basic/package.json, webdriverjs/basic/package.json, webdriverjs/manual-mode/package.json, webdriverjs/testing/package.json, webdriverjs/typescript-multi-page/package.json
=> fix(ci): add smoke tests

wdio-test-runner/typescript/basic/package.json, wdio-test-runner/typescript/global-config/package.json, wdio-test-runner/typescript/manual-mode/package.json, wdio-test-runner/typescript/typescript-multi-page/package.json, wdio/global-config/package.json, wdio/manual-mode/package.json, wdio/typescript-multi-page/package.json, wdio/v7/typescript-basic/package.json, webdriverjs/basic/package.json, webdriverjs/global-config/package.json, webdriverjs/manual-mode/package.json, webdriverjs/testing/package.json, webdriverjs/typescript-multi-page/package.json
Fixes broken tests preventing merges, e.g. #236
No QA required
=> chore: upgrade chromedriver

java/selenium/manual-mode/pom.xml, java/selenium/manual-mode/src/main/java/com/deque/watcher_examples/selenium/ManualMode.java, java/selenium/manual-mode/src/test/java/com/deque/watcher_examples/selenium/ManualModeTest.java, java/selenium/multi-page/pom.xml, java/selenium/multi-page/src/main/java/com/deque/watcher_examples/selenium/MultiPage.java, java/selenium/multi-page/src/test/java/com/deque/watcher_examples/selenium/MultiPageTest.java
Closes [@axe-watcher#97](https://github.com/dequelabs/axe-watcher/issues/97)
=> feat(java): add Selenium manual mode and multipage tests
